### ISSUE TITLE
How to download 'metaeval/folio' datasets,

### ISSUE THREAD

**Issue by kochsnow** [benlipkin/linc#1]
I have countered with issue that downloading 'metaeval/folio' datasets, since it might not be available on huggingface.
Could you tell me how to download such dataset?

**Comment by benlipkin** [comment]
Sorry about that. The dataset was moved on HF, and I've now updated the path to reflect this (https://github.com/benlipkin/linc/commit/718dfe8fae342028a837a96096e5e1e412ad4f2e). Pull the latest changes, and let me know if you're still facing any issues.
